FROM bitnami/spark:3.4.2

USER root
WORKDIR /opt/bitnami/spark/work

# Copy Spark job code and requirements into image (backup for build context)
COPY ./spark_jobs ./spark_jobs
COPY ./requirements.txt .
COPY ./.env .

# Install Python dependencies for Spark job
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 4040 7077